import "./global.css";
import Nav from "@/components/Nav";
import NoiseBg from "@/components/Noise/NoiseBg";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ overflowX: "hidden", maxWidth: "100vw" }}>
      <body
        style={{
          overflowX: "hidden",
          overflowY: "auto",
          maxWidth: "100%",
          margin: 0,
          padding: 0,
          height: "auto",
          minHeight: "100vh",
        }}
      >
        <div className="fixed top-0 left-0 right-0 bottom-0 bg-platinum -z-50" />
        <div className="fixed top-0 left-0 right-0 bottom-0 -z-40">
          <NoiseBg />
        </div>
        <Nav />
        <main className="relative z-0">{children}</main>
      </body>
    </html>
  );
}
